global:
  scrape_interval: 10s

scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets: ['fastapi-app:8000']
  - job_name: golang
    static_configs:
      - targets: ['golang-app:8081']
